//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoClassLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_log
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string User_Id { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string Input_Data { get; set; }
        public Nullable<System.DateTime> Input_Date { get; set; }
        public string Output_Data { get; set; }
        public Nullable<System.DateTime> Output_Date { get; set; }
        public string Log_Date { get; set; }
        public Nullable<int> result_code { get; set; }
        public string result_desc { get; set; }
    }
}
